### ISSUE TITLE
archives.md

### ISSUE THREAD

**Issue by Arty2** [gohugoio/hugoBasicExample#64]
Should the [archives.md](https://github.com/gohugoio/hugoBasicExample/blob/e4440a1/content/archives.md) page have a type of `posts` instead of `section`?
This doesn’t seem to populate the page in theme tests, or am I doing something wrong?
What is more, there’s no `archives` layout mentioned in the docs at all.

```yaml
---
date: 2019-05-28
type: section
layout: "archives"
---
```
